---
- name: install apache on web servers (ubuntu)
  ansible.builtin.apt:
    name:
      - apache2
      - libapache2-mod-php
  when: ansible_facts["distribution"] == "Ubuntu"

- name: install apache on web servers (fedora)
  tags: apache,fedora
  ansible.builtin.dnf:
    name: httpd
  when: ansible_facts["distribution"] == "Fedora"

- name: ensure apache is running (ubuntu)
  tags: apache,ubuntu
  ansible.builtin.service:
    name: apache2
    state: started
  when: ansible_facts["distribution"] == "Ubuntu"

- name: ensure apache is running (fedora)
  tags: apache,fedora
  ansible.builtin.service:
    name: httpd
    state: started
  when: ansible_facts["distribution"] == "Fedora"

- name: change email address for admin
  tags: apache,fedora
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin someone@somewhere.net
  when: ansible_facts["distribution"] == "Fedora"
  register: httpd

- name: restart httpd (fedora)
  tags: apache,fedora
  ansible.builtin.service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy html file for site
  tags: apache,ubuntu
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
