---
- name: create a user
  tags: always
  ansible.builtin.user:
    name: simone
    group: root

- name: add sudoers file for simone
  tags: always
  ansible.builtin.copy:
    src: sudoer_simone
    dest: /etc/sudoers.d/simone
    owner: root
    group: root
    mode: 0440

- name: add ssh key for simone user
  tags: always
  ansible.posix.authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIARPwultjqH+Y9QrUGys2rqFaJz2B1nVtEiNLktXuy4X frances@ubuntu-ws"
